/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * This part needs to get included in the compilation unit where
 * blocking_handler gets defined due to the way #pragma works.
 */

/** @defgroup CM3_nvic_isrdecls_STM32F4 User interrupt service routines (ISR)
   defaults for STM32 F4 series
    @ingroup CM3_nvic_isrdecls

    @{*/

#include "libopencm3/stm32/f4/handler.h"
